<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DapperMegaSalesAnalytics.DataAccessLayer\DapperMegaSalesAnalytics.DataAccessLayer.csproj" />
    <ProjectReference Include="..\DapperMegaSalesAnalytics.DtoLayer\DapperMegaSalesAnalytics.DtoLayer.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>



